[application]

[web.app]

[bundle]
identifier = "com,Andy.rustEan13"
publisher = "Andy"

# HTML title tag content
title = "rust-ean13"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
